# Generated by Django 2.0.4 on 2019-08-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respirology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_patient_id', models.FloatField(blank=True, db_column='Unique Patient ID', null=True)),
                ('patient_id', models.CharField(blank=True, db_column='Patient ID', max_length=255, null=True)),
                ('appointment_duration', models.FloatField(blank=True, db_column='Appointment Duration', null=True)),
                ('appointment_date', models.DateTimeField(blank=True, db_column='Appointment Date', null=True)),
                ('provider_name', models.CharField(blank=True, db_column='Provider Name', max_length=255, null=True)),
                ('cpso', models.CharField(blank=True, db_column='CPSO', max_length=255, null=True)),
                ('checkin_time', models.DateTimeField(blank=True, db_column='CheckIn Time', null=True)),
                ('checkout_time', models.CharField(blank=True, db_column='CheckOut Time', max_length=255, null=True)),
                ('roomed_time', models.CharField(blank=True, db_column='Roomed Time', max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, db_column='DEPARTMENT_NAME', max_length=255, null=True)),
                ('visit_type', models.CharField(blank=True, db_column='VISIT TYPE', max_length=255, null=True)),
                ('appt_status', models.CharField(blank=True, db_column='APPT STATUS', max_length=255, null=True)),
                ('cancelation_date', models.CharField(blank=True, db_column='Cancelation Date', max_length=255, null=True)),
                ('cancelation_reason', models.CharField(blank=True, db_column='Cancelation Reason', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Respirology',
                'managed': False,
            },
        ),
    ]
